import { mkdir, readdir, readFile, rm, writeFile, lstat } from "node:fs/promises";
import { createHash } from "node:crypto";
import { join, relative } from "node:path";

import { STATE_DIR_NAME } from "../../core/workspace.js";

export interface WorkspaceInstallResult { readonly actions: readonly string[] }
export interface WorkspaceDoctorResult { readonly ok: boolean; readonly reports: readonly string[] }

const DIRS = [
  ".dadaia-pi/agentic",
  ".dadaia-pi/states",
  ".dadaia-pi/sessions/runtime",
  ".dadaia-pi/reports",
  ".dadaia-pi/handoff",
  ".dadaia-pi/tmp",
  ".dadaia-pi/logs",
  ".pi/prompts",
  ".agents/skills",
  "repos",
];

function rootAgents(root: string, packageRoot: string): string {
  return `# Instantiated dadaia-pi-workspace\n\nScope: this file governs the workspace root \`${root}\`.\n\n## Always-on identity rule\n\n\`${root}\` is an instantiated dadaia-pi-workspace, not the package source repository.\n\nThe package/source repository that manages and scaffolds this workspace lives at:\n\n\`\`\`text\n${packageRoot}\n\`\`\`\n\nThis mirrors the dadaia-workspace model: an instantiated workspace contains a managed source repo under \`repos/\` that provides scaffold/install/doctor logic.\n\n## Generated workspace surface\n\n- Runtime state: \`.dadaia-pi/\`\n- Staged package assets: \`.dadaia-pi/agentic/\`\n- Workspace skills projection: \`.agents/skills/\`\n- Pi project-local prompts/settings: \`.pi/\`\n- Managed repositories: \`repos/\`\n\n## Rules\n\n1. Runtime state belongs under \`.dadaia-pi/\`; never create \`.dadaia-pi/\` inside managed repositories.\n2. Workspace skills/prompts are generated by \`dadaia-pi workspace install\`; do not hand-edit generated projections.\n3. To repair drift, run \`dadaia-pi workspace install\` and then \`dadaia-pi workspace doctor\`.\n4. Do not use symlink projections.\n5. Before production edits inside a managed context repo, read that repo's \`AGENTS.md\`, \`specs/constitution.md\`, active release artifacts, and task reservation.\n6. Reports belong under \`.dadaia-pi/reports/<context>/\`; machine handoffs belong under \`.dadaia-pi/handoff/<context>/\`.\n`;
}

const SCOPED: Record<string, string> = {
  ".dadaia-pi/AGENTS.md": "# .dadaia-pi runtime state\n\nMachine/runtime state for the instantiated dadaia-pi-workspace. Do not commit secrets. Prefer CLI commands over direct edits.\n",
  ".dadaia-pi/states/AGENTS.md": "# .dadaia-pi/states\n\nMachine-owned state. Do not edit directly unless implementing the workspace manager.\n",
  ".dadaia-pi/reports/AGENTS.md": "# .dadaia-pi/reports\n\nHuman-readable additive reports. Use timestamped collision-safe names.\n",
  ".dadaia-pi/handoff/AGENTS.md": "# .dadaia-pi/handoff\n\nMachine-readable handoff JSON. Validate before relying on it.\n",
  ".dadaia-pi/tmp/AGENTS.md": "# .dadaia-pi/tmp\n\nTemporary files only. Safe to clean.\n",
};

async function exists(path: string): Promise<boolean> { try { await lstat(path); return true; } catch { return false; } }
async function sha(path: string): Promise<string> { return createHash("sha256").update(await readFile(path)).digest("hex"); }
async function writeIfChanged(path: string, content: string, actions: string[]): Promise<void> {
  await mkdir(join(path, ".."), { recursive: true });
  if (await exists(path)) {
    const current = await readFile(path, "utf8");
    if (current === content) { actions.push(`[skip] ${path}`); return; }
  }
  await writeFile(path, content, "utf8"); actions.push(`[ok] ${path}`);
}

async function files(dir: string): Promise<string[]> {
  const out: string[] = [];
  if (!(await exists(dir))) return out;
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...await files(p)); else if (e.isFile()) out.push(p);
  }
  return out.sort();
}

async function copyTree(srcDir: string, dstDir: string, actions: string[]): Promise<void> {
  if (!(await exists(srcDir))) return;
  const managed = new Set<string>();
  for (const src of await files(srcDir)) {
    const rel = relative(srcDir, src);
    managed.add(rel);
    const dst = join(dstDir, rel);
    await mkdir(join(dst, ".."), { recursive: true });
    if ((await exists(dst)) && (await sha(src)) === (await sha(dst))) { actions.push(`[skip] ${dst}`); continue; }
    await writeFile(dst, await readFile(src)); actions.push(`[ok] ${dst}`);
  }
  for (const dst of await files(dstDir)) {
    const rel = relative(dstDir, dst);
    if (!managed.has(rel)) { await rm(dst); actions.push(`[prune] ${dst}`); }
  }
}

async function manifest(root: string, packageRoot: string): Promise<void> {
  const skills = await files(join(root, STATE_DIR_NAME, "agentic", "skills"));
  const prompts = await files(join(root, STATE_DIR_NAME, "agentic", "prompts"));
  const entries = [];
  for (const file of [...skills, ...prompts]) entries.push({ path: relative(root, file).replaceAll("\\", "/"), sha256: await sha(file) });
  await writeFile(join(root, STATE_DIR_NAME, "agentic", "manifest.json"), JSON.stringify({ schemaVersion: 1, packageRoot: relative(root, packageRoot).replaceAll("\\", "/"), generatedAt: new Date().toISOString(), entries }, null, 2) + "\n", "utf8");
}

export async function initWorkspace(root: string, packageRoot: string, skipAssets = false): Promise<WorkspaceInstallResult> {
  const actions: string[] = [];
  for (const dir of DIRS) { await mkdir(join(root, dir), { recursive: true }); actions.push(`[dir] ${join(root, dir)}`); }
  if (!(await exists(join(root, STATE_DIR_NAME, "states", "spec_contexts.json")))) await writeFile(join(root, STATE_DIR_NAME, "states", "spec_contexts.json"), JSON.stringify({ schemaVersion: 1, contexts: [] }, null, 2) + "\n", "utf8");
  if (!skipAssets) actions.push(...(await installWorkspace(root, packageRoot)).actions);
  return { actions };
}

export async function installWorkspace(root: string, packageRoot: string): Promise<WorkspaceInstallResult> {
  const actions: string[] = [];
  for (const dir of DIRS) await mkdir(join(root, dir), { recursive: true });
  await copyTree(join(packageRoot, "skills"), join(root, STATE_DIR_NAME, "agentic", "skills"), actions);
  await copyTree(join(packageRoot, "prompts"), join(root, STATE_DIR_NAME, "agentic", "prompts"), actions);
  await copyTree(join(root, STATE_DIR_NAME, "agentic", "skills"), join(root, ".agents", "skills"), actions);
  await copyTree(join(root, STATE_DIR_NAME, "agentic", "prompts"), join(root, ".pi", "prompts"), actions);
  await writeIfChanged(join(root, "AGENTS.md"), rootAgents(root, packageRoot), actions);
  for (const [rel, content] of Object.entries(SCOPED)) await writeIfChanged(join(root, rel), content, actions);
  await writeIfChanged(join(root, ".pi", "settings.json"), JSON.stringify({ packages: [relative(root, packageRoot).replaceAll("\\", "/")] }, null, 2) + "\n", actions);
  await manifest(root, packageRoot);
  return { actions };
}

export async function doctorWorkspaceInstall(root: string, packageRoot: string): Promise<WorkspaceDoctorResult> {
  const reports: string[] = [];
  function report(ok: boolean, label: string) { reports.push(`${ok ? "[ok]" : "[drift]"} ${label}`); }
  const pairs: readonly (readonly [string, string])[] = [
    [join(packageRoot, "skills"), join(root, STATE_DIR_NAME, "agentic", "skills")],
    [join(root, STATE_DIR_NAME, "agentic", "skills"), join(root, ".agents", "skills")],
    [join(packageRoot, "prompts"), join(root, STATE_DIR_NAME, "agentic", "prompts")],
    [join(root, STATE_DIR_NAME, "agentic", "prompts"), join(root, ".pi", "prompts")],
  ];
  for (const [src, dst] of pairs) {
    const srcFiles = await files(src);
    const dstFiles = await files(dst);
    const rels = new Set([...srcFiles.map((file) => relative(src, file)), ...dstFiles.map((file) => relative(dst, file))]);
    for (const rel of rels) {
      const srcPath = join(src, rel);
      const dstPath = join(dst, rel);
      report((await exists(srcPath)) && (await exists(dstPath)) && (await sha(srcPath)) === (await sha(dstPath)), `${relative(root, dst)}/${rel}`.replaceAll("\\", "/"));
    }
  }
  report((await exists(join(root, "AGENTS.md"))) && (await readFile(join(root, "AGENTS.md"), "utf8")) === rootAgents(root, packageRoot), "AGENTS.md");
  const ok = reports.every(r => r.startsWith("[ok]"));
  return { ok, reports };
}
