"""Workspace scaffold/install/doctor operations."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from .file_ops import copy_tree_managed, write_if_missing, write_json_atomic, write_text_atomic

DIRS = [
    ".dadaia-pi/agentic",
    ".dadaia-pi/states",
    ".dadaia-pi/sessions/runtime",
    ".dadaia-pi/reports",
    ".dadaia-pi/handoff",
    ".dadaia-pi/tmp",
    ".dadaia-pi/logs",
    ".pi/prompts",
    ".agents/skills",
    "repos",
]

SCOPED = {
    ".dadaia-pi/AGENTS.md": "# .dadaia-pi runtime state\n\nMachine/runtime state for the instantiated dadaia-pi-workspace. Do not commit secrets. Prefer CLI commands over direct edits.\n",
    ".dadaia-pi/states/AGENTS.md": "# .dadaia-pi/states\n\nMachine-owned state. Do not edit directly unless implementing the workspace manager.\n",
    ".dadaia-pi/reports/AGENTS.md": "# .dadaia-pi/reports\n\nHuman-readable additive reports. Use timestamped collision-safe names.\n",
    ".dadaia-pi/handoff/AGENTS.md": "# .dadaia-pi/handoff\n\nMachine-readable handoff JSON. Validate before relying on it.\n",
    ".dadaia-pi/tmp/AGENTS.md": "# .dadaia-pi/tmp\n\nTemporary files only. Safe to clean.\n",
}


def root_agents(root: Path, package_root: Path) -> str:
    return f"""# Instantiated dadaia-pi-workspace

Scope: this file governs the workspace root `{root}`.

## Always-on identity rule

`{root}` is an instantiated dadaia-pi-workspace, not the package source repository.

The package/source repository that manages and scaffolds this workspace lives at:

```text
{package_root}
```

This mirrors the dadaia-workspace model: an instantiated workspace contains a managed source repo under `repos/` that provides scaffold/install/doctor logic.

## Generated workspace surface

- Runtime state: `.dadaia-pi/`
- Staged package assets: `.dadaia-pi/agentic/`
- Workspace skills projection: `.agents/skills/`
- Pi project-local prompts/settings: `.pi/`
- Managed repositories: `repos/`

## Rules

1. Runtime state belongs under `.dadaia-pi/`; never create `.dadaia-pi/` inside managed repositories.
2. Workspace skills/prompts are generated by `dadaia-pi workspace install`; do not hand-edit generated projections.
3. To repair drift, run `dadaia-pi workspace install` and then `dadaia-pi workspace doctor`.
4. Do not use symlink projections.
5. Before production edits inside a managed context repo, read that repo's `AGENTS.md`, `specs/constitution.md`, active release artifacts, and task reservation.
6. Reports belong under `.dadaia-pi/reports/<context>/`; machine handoffs belong under `.dadaia-pi/handoff/<context>/`.
"""


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _files(path: Path) -> list[Path]:
    return sorted(item for item in path.rglob("*") if item.is_file()) if path.exists() else []


def _ensure_dirs(root: Path) -> list[str]:
    actions: list[str] = []
    for rel in DIRS:
        path = root / rel
        path.mkdir(parents=True, exist_ok=True)
        actions.append(f"[dir] {path}")
    return actions


def _write_changed(path: Path, content: str) -> str:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return f"[skip] {path}"
    write_text_atomic(path, content)
    return f"[ok] {path}"


def _manifest(root: Path, package_root: Path) -> None:
    entries = []
    for base in [root / ".dadaia-pi" / "agentic" / "skills", root / ".dadaia-pi" / "agentic" / "prompts"]:
        for file in _files(base):
            entries.append({"path": file.relative_to(root).as_posix(), "sha256": _sha(file)})
    package_value = package_root.relative_to(root).as_posix() if package_root.is_relative_to(root) else str(package_root)
    write_json_atomic(root / ".dadaia-pi" / "agentic" / "manifest.json", {"schemaVersion": 1, "packageRoot": package_value, "generatedAt": "python-cli", "entries": entries})


def init_workspace(root: Path, package_root: Path, *, skip_assets: bool = False) -> dict[str, list[str]]:
    root = root.resolve()
    package_root = package_root.resolve()
    actions = _ensure_dirs(root)
    write_if_missing(root / ".dadaia-pi" / "states" / "spec_contexts.json", json.dumps({"schemaVersion": 1, "contexts": []}, indent=2) + "\n")
    if not skip_assets:
        actions.extend(install_workspace(root, package_root)["actions"])
    return {"actions": actions}


def install_workspace(root: Path, package_root: Path) -> dict[str, list[str]]:
    root = root.resolve()
    package_root = package_root.resolve()
    _ensure_dirs(root)
    actions: list[str] = []
    actions.extend(copy_tree_managed(package_root / "skills", root / ".dadaia-pi" / "agentic" / "skills"))
    actions.extend(copy_tree_managed(package_root / "prompts", root / ".dadaia-pi" / "agentic" / "prompts"))
    actions.extend(copy_tree_managed(root / ".dadaia-pi" / "agentic" / "skills", root / ".agents" / "skills"))
    actions.extend(copy_tree_managed(root / ".dadaia-pi" / "agentic" / "prompts", root / ".pi" / "prompts"))
    actions.append(_write_changed(root / "AGENTS.md", root_agents(root, package_root)))
    for rel, content in SCOPED.items():
        actions.append(_write_changed(root / rel, content))
    package_value = package_root.relative_to(root).as_posix() if package_root.is_relative_to(root) else str(package_root)
    actions.append(_write_changed(root / ".pi" / "settings.json", json.dumps({"packages": [package_value]}, indent=2) + "\n"))
    _manifest(root, package_root)
    return {"actions": actions}


def _rich_doctor_issues(root: Path, package_root: Path) -> list[dict[str, Any]]:
    issues: list[dict[str, Any]] = []
    state = root / ".dadaia-pi"
    # Workflow manifests: must be JSON objects with core identity fields.
    workflows = state / "workflows"
    if workflows.exists():
        for path in workflows.rglob("*.json"):
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
                for field in ["workflowId", "context"]:
                    if field not in payload:
                        issues.append({"code": "PY-WORKFLOW-1", "severity": "error", "path": path.relative_to(root).as_posix(), "message": f"workflow manifest missing {field}"})
                if "verdict" not in payload:
                    issues.append({"code": "PY-WORKFLOW-1", "severity": "warning", "path": path.relative_to(root).as_posix(), "message": "legacy workflow manifest missing verdict"})
            except Exception as exc:
                issues.append({"code": "PY-WORKFLOW-1", "severity": "error", "path": path.relative_to(root).as_posix(), "message": f"malformed workflow manifest: {exc}"})
    # Release candidates: validate minimum schema and review arrays.
    rcs = state / "release-candidates"
    if rcs.exists():
        for path in rcs.rglob("*.json"):
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
                reviews = payload.get("reviews") if isinstance(payload, dict) else None
                if payload.get("schemaVersion") != 1 or not payload.get("id") or not isinstance(reviews, dict):
                    issues.append({"code": "PY-RC-1", "severity": "error", "path": path.relative_to(root).as_posix(), "message": "invalid release candidate record"})
                elif not all(isinstance(reviews.get(k), list) for k in ["qa", "security", "code"]):
                    issues.append({"code": "PY-RC-1", "severity": "error", "path": path.relative_to(root).as_posix(), "message": "release candidate reviews.qa/security/code must be arrays"})
            except Exception as exc:
                issues.append({"code": "PY-RC-1", "severity": "error", "path": path.relative_to(root).as_posix(), "message": f"malformed release candidate: {exc}"})
    # Handoffs: catch malformed JSON; schema detail is covered by handoff validate.
    handoffs = state / "handoff"
    if handoffs.exists():
        for path in handoffs.rglob("*.handoff.json"):
            try:
                json.loads(path.read_text(encoding="utf-8"))
            except Exception as exc:
                issues.append({"code": "PY-HANDOFF-1", "severity": "error", "path": path.relative_to(root).as_posix(), "message": f"malformed handoff: {exc}"})
    # Authority boundary: extension adapter should mention Python bridge.
    ext = package_root / "extensions" / "dadaia-pi.ts"
    if ext.exists() and "pi-bridge" not in ext.read_text(encoding="utf-8"):
        issues.append({"code": "PY-AUTHORITY-1", "severity": "warning", "path": ext.relative_to(package_root).as_posix(), "message": "Pi extension does not appear to delegate through Python bridge"})
    package_json = package_root / "package.json"
    if package_json.exists():
        try:
            package = json.loads(package_json.read_text(encoding="utf-8"))
            if (package.get("bin") or {}).get("dadaia-pi") != "./bin/dadaia-pi.mjs":
                issues.append({"code": "PY-AUTHORITY-2", "severity": "error", "path": "package.json", "message": "npm dadaia-pi bin must delegate through ./bin/dadaia-pi.mjs"})
        except Exception as exc:
            issues.append({"code": "PY-AUTHORITY-2", "severity": "error", "path": "package.json", "message": f"cannot read package authority metadata: {exc}"})
    if not (package_root / "src" / "cli" / "LEGACY.md").exists() or not (package_root / "src" / "features" / "LEGACY.md").exists():
        issues.append({"code": "PY-AUTHORITY-3", "severity": "warning", "path": "src/", "message": "legacy TypeScript lifecycle trees should carry LEGACY.md authority boundary markers"})
    return issues


def doctor_workspace_install(root: Path, package_root: Path) -> dict[str, object]:
    root = root.resolve()
    package_root = package_root.resolve()
    reports: list[str] = []
    pairs = [
        (package_root / "skills", root / ".dadaia-pi" / "agentic" / "skills"),
        (root / ".dadaia-pi" / "agentic" / "skills", root / ".agents" / "skills"),
        (package_root / "prompts", root / ".dadaia-pi" / "agentic" / "prompts"),
        (root / ".dadaia-pi" / "agentic" / "prompts", root / ".pi" / "prompts"),
    ]
    for src, dst in pairs:
        rels = {file.relative_to(src).as_posix() for file in _files(src)} | {file.relative_to(dst).as_posix() for file in _files(dst)}
        for rel in sorted(rels):
            src_path = src / rel
            dst_path = dst / rel
            ok = src_path.exists() and dst_path.exists() and _sha(src_path) == _sha(dst_path)
            label = f"{dst.relative_to(root).as_posix()}/{rel}"
            reports.append(f"{'[ok]' if ok else '[drift]'} {label}")
    agents_ok = (root / "AGENTS.md").exists() and (root / "AGENTS.md").read_text(encoding="utf-8") == root_agents(root, package_root)
    reports.append(f"{'[ok]' if agents_ok else '[drift]'} AGENTS.md")
    issues = _rich_doctor_issues(root, package_root.resolve())
    return {
        "ok": all(item.startswith("[ok]") for item in reports) and not any(item.get("severity") == "error" for item in issues),
        "authority": "python",
        "mixedAuthorityDrift": [item for item in issues if item.get("code") == "PY-AUTHORITY-1"],
        "issues": issues,
        "reports": reports,
    }


def project_settings(root: Path, source: str) -> dict[str, object]:
    path = root.resolve() / ".pi" / "settings.json"
    write_text_atomic(path, json.dumps({"packages": [source]}, indent=2) + "\n")
    return {"path": str(path), "packages": [source]}
